name: Build and push docker images to Docker Hub

on:
  workflow_dispatch:
  push:

jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get environment
        id: env_get
        run: |
          echo "env_name=production" >> "$GITHUB_OUTPUT"
        

  build_and_push_to_registry:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: ${{needs.prepare.outputs.env_name}}
    steps:
      - name: Get environment
        run: |
          echo ${{needs.prepare.outputs.env_name}}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Repository
        uses : docker/login-action@v3
        with : 
          username : ${{SECRETS.DOCKERHUB_EMAIL}}
          password : ${{SECRETS.DOCKERHUB_PASSWORD}}

      - name : build and push docker image to registry
        uses : docker/build-push-action@v5
        with :
          context : ./
          push : true
          tags : joshuadavid9219/securin-cve
      
